# Generated by Django 4.2.17 on 2026-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0025_client_and_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="country_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Country"),
                    ("+1", "United States (+1)"),
                    ("+1", "Canada (+1)"),
                    ("+44", "United Kingdom (+44)"),
                    ("+61", "Australia (+61)"),
                    ("+81", "Japan (+81)"),
                    ("+86", "China (+86)"),
                    ("+91", "India (+91)"),
                    ("+55", "Brazil (+55)"),
                    ("+33", "France (+33)"),
                    ("+49", "Germany (+49)"),
                    ("+39", "Italy (+39)"),
                    ("+34", "Spain (+34)"),
                    ("+31", "Netherlands (+31)"),
                    ("+46", "Sweden (+46)"),
                    ("+47", "Norway (+47)"),
                    ("+45", "Denmark (+45)"),
                    ("+43", "Austria (+43)"),
                    ("+41", "Switzerland (+41)"),
                    ("+32", "Belgium (+32)"),
                    ("+353", "Ireland (+353)"),
                    ("+358", "Finland (+358)"),
                    ("+48", "Poland (+48)"),
                    ("+420", "Czech Republic (+420)"),
                    ("+36", "Hungary (+36)"),
                    ("+40", "Romania (+40)"),
                    ("+30", "Greece (+30)"),
                    ("+90", "Turkey (+90)"),
                    ("+966", "Saudi Arabia (+966)"),
                    ("+971", "United Arab Emirates (+971)"),
                    ("+974", "Qatar (+974)"),
                    ("+965", "Kuwait (+965)"),
                    ("+968", "Oman (+968)"),
                    ("+212", "Morocco (+212)"),
                    ("+234", "Nigeria (+234)"),
                    ("+27", "South Africa (+27)"),
                    ("+260", "Zambia (+260)"),
                    ("+263", "Zimbabwe (+263)"),
                    ("+256", "Uganda (+256)"),
                    ("+254", "Kenya (+254)"),
                    ("+255", "Tanzania (+255)"),
                ],
                default="",
                max_length=5,
                null=True,
            ),
        ),
    ]
